### ISSUE TITLE
Identifier 'e' has already been declared 

### ISSUE THREAD

**Issue by BigBuckBunny** [djyde/cusdis#230]
Hi,

Using "@sveltejs/kit": "1.0.1", and your JS code, everything works great, except if I change routes to a different article, without even commenting, I get the following error with no comment section:

Uncaught SyntaxError: Identifier 'e' has already been declared (at cusdis.es.js:1:1)

So, first time I see the comment section, I can comment and the webhook works great on approval. But if I change to a different article without reloading the whole page I get that error.

Thanks

**Comment by huyixi** [comment]
I meet the same problem.
Uncaught SyntaxError: Identifier 'e' has already been declared (at cusdis.es.js:1:1)
I using cusdis in hugo.
This is my code: 
```
<div id="cusdis_thread" data-host="https://cusdis.com"
  data-app-id="-"
  data-page-id="{{ print .File.UniqueID .Site.Language.Lang }}"
  data-page-url="{{ .Permalink }}"
  data-page-title="{{ .Title }}"></div>
<script async defer src="https://cusdis.com/js/cusdis.es.js"></script>
```

**Comment by codebyamir** [comment]
This appears to be a variable scoping issue.  

When you have multiple obfuscated Javascript files loaded by the same page, it has the potential to collide and produce this type of error.

A fix is to wrap the code in braces.  The downside is that you'll need to host the JS file yourself.

```js
window.CUSDIS={};
{
  let e;
  ...
};



```
