### ISSUE TITLE
Disqus comment import only partially done

### ISSUE THREAD

**Issue by frostming** [djyde/cusdis#44]
Hi, I hosted Cusdis with Vercel + Postgres combination and I failed to import comments from Disqus. It returned "Something went wrong" 500 error.

For what it worth, the exported XML contains some comments that were imported from my own developed Blog engine. So some fields were faked or missing, but they were displayed well on Disqus.

Attach the Disqus XML below
[flog-1-2021-04-23T09_34_33.817420-all.xml.gz](https://github.com/djyde/cusdis/files/6365387/flog-1-2021-04-23T09_34_33.817420-all.xml.gz)

**Comment by djyde** [comment]
Thank you. I will take a look later.

**Comment by djyde** [comment]
Did you see some logs on Vercel functions log when it failed?

**Comment by frostming** [comment]
Yes
```
[POST] /api/project/aa4ece8e-cc79-4c64-a92d-83bc53b09d1a/data/import
21:44:42:67
2021-04-23T13:44:47.255Z	83faf46e-922a-4eb8-bc8d-eff37a45ecf1	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Foreign key constraint failed on the field: `comments_parentId_fkey (index)`","reason":{"errorType":"Error","errorMessage":"Foreign key constraint failed on the field: `comments_parentId_fkey (index)`","code":"P2003","clientVersion":"2.21.2","meta":{"field_name":"comments_parentId_fkey (index)"},"stack":["Error: Foreign key constraint failed on the field: `comments_parentId_fkey (index)`","    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:34780:17)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async /var/task/.next/server/pages/api/project/[projectId]/data/import.js:432:7","    at async Promise.all (index 2)","    at async data_service_DataService.importFromDisqus (/var/task/.next/server/pages/api/project/[projectId]/data/import.js:429:5)","    at async /var/task/.next/server/pages/api/project/[projectId]/data/import.js:504:24"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Foreign key constraint failed on the field: `comments_parentId_fkey (index)`","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:94:32)"]}
```

**Comment by frostming** [comment]
It seems that the parent comment that is referred to isn't created yet.

**Comment by djyde** [comment]
> It seems that the parent comment that is referred to isn't created yet.

I think so. I should make sure the parent comment upsert successfully first then upsert the children.

**Comment by frostming** [comment]
I finally workaround this by splitting the XML into comments without parents and the rest. Then upload them separately. Thanks to Cusdis, keep going on.
